### ISSUE TITLE
Missing Assets/Scripts/UTK/ProjectKaya/SettingData.asset

### ISSUE THREAD

**Issue by connffuused** [UnityKorea/ProjectKaya#3]
```Assets/Scripts/UTK/ProjectKaya/SettingData.asset```

스크립트가 삭제된 오브젝트가 존재합니다.
4b5a8a8fad26c1879b9d94a3ab5a69bbf2d03ef1 커밋에서 삭제된 스크립트로 보입니다.

**Comment by SangyunYi** [comment]
설정 정보 저장을 위해 객체 생성해두었다가, 정리과정에서 불필요한 리소스가 남아있었습니다. 감사합니다.
